config/routes.rb
MangoHandcart::Engine.routes.draw do

  resources :ip_addresses
  resources :dns_records
  root to: 'dns_records#index'

end

app/models/mango_handcart/concerns/handcarts.rb
module MangoHandcart::Concerns::Handcarts
  extend ActiveSupport::Concern

  included do
    belongs_to :dns_record, class_name: MangoHandcart.dns_record_class.to_s
    has_many :ip_addresses, dependent: :destroy, class_name: "MangoHandcart::IpAddress", foreign_key: "handcart_id"

    # Nuke the dns_record
    before_destroy { |handcart| handcart.dns_record.destroy if handcart.dns_record.present? }
  end

  module ClassMethods
    # Try to formulate a path to view the handcart show page
    def handcart_show_path(handcart)
      if MangoHandcart.handcart_show_path.present?
        # Load it straight from the config
        "/#{MangoHandcart.handcart_show_path}/#{handcart.to_param}"
      else
        if Rails.application.routes.url_helpers.respond_to?("#{MangoHandcart.handcart_class.model_name.singular}_path".to_sym)
          # Is there one already defined
          Rails.application.routes.url_helpers.send("#{MangoHandcart.handcart_class.model_name.singular}_path", handcart.to_param)
        else
          # Shot in the dark
          "/#{MangoHandcart.handcart_class.model_name.route_key}/#{handcart.to_param}"
        end
      end
    end
  end

end

app/models/mango_handcart/dns_record.rb
module MangoHandcart
  class DnsRecord < ActiveRecord::Base
    has_one :handcart, class_name: MangoHandcart.handcart_class.to_s

    validates :name, presence: true

    # Make sure we don't assign reserved subdomains
    validates :subdomain,
      presence: true,
      exclusion: { in: MangoHandcart.reserved_subdomains }

    # Make sure they're unique unless we enable A-Record lookups
    validates :subdomain, uniqueness: { case_sensitive: false, scope: [:domain] }, unless: lambda { MangoHandcart.enable_a_record_lookups }

    scope :allocated, -> { DnsRecord.includes(:handcart).where("#{MangoHandcart.handcart_class.model_name.plural}.dns_record_id IS NOT NULL").references(:handcart) }
    scope :unallocated, -> { DnsRecord.includes(:handcart).where("#{MangoHandcart.handcart_class.model_name.plural}.dns_record_id IS NULL").references(:handcart) }
    scope :unallocated_or_current, lambda { |handcart| DnsRecord.includes(:handcart).where("#{MangoHandcart.handcart_class.model_name.plural}.dns_record_id IS NULL OR #{MangoHandcart.handcart_class.model_name.plural}.dns_record_id IN (?)", handcart.try(:dns_record_id)).references(:handcart) }
    scope :ordered, -> { order("mango_handcart_dns_records.subdomain ASC") }

    before_save :normalize_subdomain

    # Lookup a DNS record by the subdomain/domain
    def self.lookup(request)
      if MangoHandcart.enable_a_record_lookups
        # Find it by the domain AND subdomain
        find_by(domain: request.domain, subdomain: request.subdomain)
      else
        # Just find it by the subdomain
        find_by(subdomain: request.subdomain)
      end
    end

    def self.matches?(request)
      my_dns_record = DnsRecord.lookup(request)
      if my_dns_record && request.subdomain.present? && !MangoHandcart.reserved_subdomains.include?(request.subdomain) && my_dns_record.handcart
        if my_dns_record.handcart.respond_to?(:active?)
          my_dns_record.handcart.active?
        else
          # Just default to true since we found the record
          true
        end
      end
    end


    private

    def normalize_subdomain
      self.subdomain = subdomain.squish.gsub(/\s+|\+|\/|=|\?/, '').parameterize
    end

  end
end

app/models/mango_handcart/ip_address.rb
module MangoHandcart
  class IpAddress < ActiveRecord::Base
    belongs_to :handcart, class_name: MangoHandcart.handcart_class.to_s

    validates :address,
      presence: true,
      uniqueness: { case_sensitive: false },
      format: { with: Resolv::IPv4::Regex }

    validates :subnet_mask,
      presence: true,
      format: { with: Resolv::IPv4::Regex }

    scope :blacklisted, -> { where(blacklisted: true) }
    scope :permitted, -> { where.not(blacklisted: true) }
    scope :with_handcart, lambda { |handcart| where(handcart_id: handcart.try(:id)) }
    scope :ordered, -> { order("mango_handcart_ip_addresses.address ASC") }
  end
end

app/controllers/mango_handcart/application_controller.rb
module MangoHandcart
  class ApplicationController < ActionController::Base
  end
end

app/controllers/mango_handcart/dns_records_controller.rb
require_dependency "mango_handcart/application_controller"

module MangoHandcart
  class DnsRecordsController < ApplicationController
    before_action :set_dns_record, only: [:show, :edit, :update, :destroy]

    def index
      @dns_records = DnsRecord.all
      @dns_records = @dns_records.page(params[:page])
    end

    def show
    end

    def new
      @dns_record = DnsRecord.new
    end

    def edit
    end

    def create
      @dns_record = DnsRecord.new(safe_params)

      if @dns_record.save
        redirect_to @dns_record, notice: 'DNS Record was successfully created.'
      else
        render :new
      end
    end

    def update
      if @dns_record.update(safe_params)
        redirect_to @dns_record, notice: 'DNS Record was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @dns_record.destroy
      redirect_to dns_records_url, notice: 'DNS Record was successfully removed.'
    end


    private

    def set_dns_record
      @dns_record = DnsRecord.find(params[:id])
    end

    def safe_params
      safe_attributes = [:name, :subdomain, :domain, :tld_size, :active]
      params.require(:dns_record).permit(safe_attributes)
    end

  end
end

app/controllers/mango_handcart/ip_addresses_controller.rb
require_dependency "mango_handcart/application_controller"

module MangoHandcart
  class IpAddressesController < ApplicationController
    before_action :set_ip_address, only: [:show, :edit, :update, :destroy]

    def index
      @ip_addresses = IpAddress.all
      @ip_addresses = @ip_addresses.page(params[:page])
    end

    def show
    end

    def new
      @ip_address = IpAddress.new
    end

    def edit
    end

    def create
      @ip_address = IpAddress.new(safe_params)

      if @ip_address.save
        redirect_to @ip_address, notice: 'IP Address was successfully created.'
      else
        render :new
      end
    end

    def update
      if @ip_address.update(safe_params)
        redirect_to @ip_address, notice: 'IP Address was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @ip_address.destroy
      redirect_to ip_addresses_url, notice: 'IP Address was successfully removed.'
    end


    private

    def set_ip_address
      @ip_address = IpAddress.find(params[:id])
    end

    def safe_params
      safe_attributes = [:address, :subnet_mask, :handcart_id, :blacklisted]
      params.require(:ip_address).permit(safe_attributes)
    end

  end
end

app/helpers/mango_handcart/application_helper.rb
module MangoHandcart
  module ApplicationHelper
    def title(page_title, show_sub_title = true, options={})
      content_for(:title) { page_title }
      if show_sub_title
        sub_title(page_title)
      end
    end

    def sub_title(sub_title, options={})
      content_for(:sub_title) { sub_title }
    end
  end
end

app/helpers/mango_handcart/bootstrap_flash_helper.rb
module MangoHandcart
  module BootstrapFlashHelper
    ALERT_TYPES = [:danger, :info, :success, :warning] unless const_defined?(:ALERT_TYPES)

    def bootstrap_flash
      flash_messages = []
      flash.each do |type, message|
        # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
        next if message.blank?

        type = type.to_sym
        type = :success if type == :notice
        type = :danger if type == :error
        next unless ALERT_TYPES.include?(type)

        Array(message).each do |msg|
          text = content_tag(:div,
                             content_tag(:button, raw("&times;"), class: "close", "data-dismiss" => "alert") +
                             msg.html_safe, class: "alert fade in alert-#{type}")
          flash_messages << text if msg
        end
      end
      flash_messages.join("\n").html_safe
    end
  end
end

app/views/layouts/mango_handcart/_navbar.html.haml
#navbar-collapse-1.collapse.navbar-collapse
  %ul.nav.navbar-nav
    %li
      = link_to main_app.root_path do
        %span.glyphicon.glyphicon-arrow-left
        Back to
        = t(".main_app")
    %li{class: (params[:controller] == "mango_handcart/dns_records") ? "active" : nil}
      = link_to mango_handcart.root_path do
        %span.glyphicon.glyphicon-th-list
        = t(".dns_records")
    - unless (MangoHandcart.ip_authorization.ip_authorization_strategy == :none)
      %li{class: (params[:controller] == "mango_handcart/ip_addresses") ? "active" : nil}
        = link_to mango_handcart.ip_addresses_path do
          %span.glyphicon.glyphicon-screenshot
          = t(".ip_addresses")

app/views/layouts/mango_handcart/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? t('.title', title: yield(:title)) : t('.default_title')
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "mango_handcart/application", media: "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png'
    = javascript_include_tag "mango_handcart/application"

  %body
    %nav.navbar.navbar-default{role: "navigation"}
      .container-fluid
        .navbar-header
          %button.navbar-toggle{"data-target" => "#navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: root_path}
            %span.glyphicon.glyphicon-home
            = t(".mango_handcart_brand")
        = render "layouts/mango_handcart/navbar"

    .container
      .row
        - if content_for?(:sidebar)
          .col-lg-9
            %div.flash-message
              = bootstrap_flash
            - if content_for?(:sub_title)
              .page-header
                %h3.sub-title.inline= content_for?(:sub_title) ? yield(:sub_title) : t('.default_sub_title')
            - if content_for?(:toolbar)
              %div#button-toolbar= yield(:toolbar)
            %div= yield
          .col-lg-3
            .well.sidebar-nav
              %ul.nav.nav-list= yield(:sidebar)
        - else
          .col-lg-12
            %div.flash-message
              = bootstrap_flash
            - if content_for?(:sub_title)
              .page-header
                %h3.sub-title.inline= content_for?(:sub_title) ? yield(:sub_title) : t('.default_sub_title')
            - if content_for?(:toolbar)
              %div#button-toolbar= yield(:toolbar)
            %div= yield
      %footer
        %p
          &copy;
          = t(".copyright", year: Date.today.year)

app/views/mango_handcart/dns_records/_form.html.haml
= simple_form_for @dns_record do |f|
  = f.error_notification

  = f.input :name
  = f.input :subdomain
  = f.input :domain
  = f.input :tld_size, as: :string
  = f.input :active, as: :select, include_blank: false

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.button :submit, class: 'btn btn-warning'
      = link_to 'Cancel', @dns_record.new_record? ? dns_records_path : dns_record_path(@dns_record), class: 'btn btn-link'

app/views/mango_handcart/dns_records/edit.html.haml
- title t(".title")

= render 'form'

app/views/mango_handcart/dns_records/index.html.haml
- title t(".dns_records")

- content_for(:toolbar) do
  .btn-group
    = link_to new_dns_record_path, class: 'btn btn-primary btn-xs', title: t(".new_dns_record") do
      %span.glyphicon.glyphicon-plus

= paginate @dns_records

%table.table.table-striped.table-hover.table-condensed
  %thead
    %tr
      %th= MangoHandcart::DnsRecord.human_attribute_name(:name)
      %th= MangoHandcart::DnsRecord.human_attribute_name(:subdomain)
      %th= MangoHandcart.handcart_class.model_name.human
      %th= MangoHandcart::DnsRecord.human_attribute_name(:domain)
      %th= MangoHandcart::DnsRecord.human_attribute_name(:tld_size)
      %th= MangoHandcart::DnsRecord.human_attribute_name(:active)
      %th
      %th
  %tbody
    - @dns_records.each do |dns_record|
      %tr
        %td= link_to dns_record.name, dns_record
        %td= dns_record.subdomain
        %td
          - if dns_record.handcart
            = link_to dns_record.handcart.try(:to_s), MangoHandcart.handcart_class.handcart_show_path(dns_record.handcart)
          - else
            None
        %td= dns_record.domain
        %td= dns_record.tld_size
        %td= dns_record.active? ? "Active" : "Inactive"
        %td.action-button
          = link_to edit_dns_record_path(dns_record), class: 'btn btn-warning btn-xs', title: t(".edit_dns_record") do
            %span.glyphicon.glyphicon-edit
        %td.action-button
          = link_to dns_record, method: :delete, data: { confirm: t(".confirm") }, class: 'btn btn-danger btn-xs', title: t(".remove_dns_record") do
            %span.glyphicon.glyphicon-remove

= paginate @dns_records

app/views/mango_handcart/dns_records/new.html.haml
- title t(".title")

= render 'form'

app/views/mango_handcart/dns_records/show.html.haml
- title t(".title", dns_record: @dns_record.name), false

.page-header
  %h3.sub-title.inline
    = t(".title", dns_record: @dns_record.name)
    %span
      = link_to edit_dns_record_path(@dns_record), class: 'btn btn-warning btn-xs', title: t(".edit_dns_record") do
        %span.glyphicon.glyphicon-edit

%table.table.table-striped.table-hover.table-condensed
  %tbody
    %tr
      %th= MangoHandcart::DnsRecord.human_attribute_name(:name)
      %td= @dns_record.name
      %th= MangoHandcart::DnsRecord.human_attribute_name(:subdomain)
      %td= @dns_record.subdomain
    %tr
      %th= MangoHandcart::DnsRecord.human_attribute_name(:domain)
      %td= @dns_record.domain
      %th= MangoHandcart::DnsRecord.human_attribute_name(:tld_size)
      %td= @dns_record.tld_size
    %tr
      %th= MangoHandcart::DnsRecord.human_attribute_name(:active)
      %td= @dns_record.active? ? "Active" : "Inactive"
      %th= MangoHandcart.handcart_class.model_name.human
      %td
        - if @dns_record.handcart
          = link_to @dns_record.handcart.try(:to_s), MangoHandcart.handcart_class.handcart_show_path(@dns_record.handcart)
        - else
          None
    %tr
      %th Created At
      %td= l(@dns_record.created_at, format: :short)
      %th Updated At
      %td= l(@dns_record.updated_at, format: :short)

app/views/mango_handcart/ip_addresses/_form.html.haml
= simple_form_for @ip_address do |f|
  = f.error_notification

  = f.input :address
  = f.input :subnet_mask
  = f.association :handcart, collection: MangoHandcart.handcart_class.all, label: MangoHandcart.handcart_class.model_name.human
  = f.input :blacklisted, as: :select, include_blank: false

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.button :submit, class: 'btn btn-warning'
      = link_to 'Cancel', @ip_address.new_record? ? ip_addresses_path : ip_address_path(@ip_address), class: 'btn btn-link'

app/views/mango_handcart/ip_addresses/edit.html.haml
- title t(".title")

= render 'form'

app/views/mango_handcart/ip_addresses/index.html.haml
- title t(".title")

- content_for(:toolbar) do
  .btn-group
    = link_to new_ip_address_path, class: 'btn btn-primary btn-xs', title: t(".new_ip_address") do
      %span.glyphicon.glyphicon-plus

= paginate @ip_addresses

%table.table.table-striped.table-hover.table-condensed
  %thead
    %tr
      %th= MangoHandcart::IpAddress.human_attribute_name(:address)
      %th= MangoHandcart::IpAddress.human_attribute_name(:subnet_mask)
      %th= MangoHandcart::IpAddress.human_attribute_name(:handcart)
      %th= MangoHandcart::IpAddress.human_attribute_name(:blacklisted)
      %th
      %th
  %tbody
    - @ip_addresses.each do |ip_address|
      %tr
        %td= link_to ip_address.address, ip_address, title: t(".view_ip_address")
        %td= ip_address.subnet_mask
        %td
          - if ip_address.handcart.present?
            = link_to ip_address.handcart.to_s, MangoHandcart.handcart_class.handcart_show_path(ip_address.handcart)
          - else
            None
        %td= ip_address.blacklisted? ? "Yes" : "No"
        %td.action-button
          = link_to edit_ip_address_path(ip_address), class: 'btn btn-xs btn-warning', title: t(".edit_ip_address") do
            %span.glyphicon.glyphicon-edit
        %td.action-button
          = link_to ip_address, method: :delete, data: { confirm: t(".confirm") }, class: 'btn btn-danger btn-xs', title: t(".remove_ip_address") do
            %span.glyphicon.glyphicon-remove

= paginate @ip_addresses

app/views/mango_handcart/ip_addresses/new.html.haml
- title t(".title")

= render 'form'

app/views/mango_handcart/ip_addresses/show.html.haml
- title t(".title", address: @ip_address.address), false

.page-header
  %h3.sub-title.inline
    = t(".title", address: @ip_address.address)
    %span
      = link_to edit_ip_address_path(@ip_address), class: 'btn btn-warning btn-xs', title: t(".edit_ip_address") do
        %span.glyphicon.glyphicon-edit

.row
  .col-lg-3.well
    %table.table.table-striped.table-condensed.table-hover.no-margin-bottom
      %tbody
        %tr
          %th= MangoHandcart::IpAddress.human_attribute_name(:address)
          %td= @ip_address.address
        %tr
          %th= MangoHandcart::IpAddress.human_attribute_name(:subnet_mask)
          %td= @ip_address.subnet_mask
        %tr
          %th= MangoHandcart::IpAddress.human_attribute_name(:handcart)
          %td
            - if @ip_address.handcart.present?
              = link_to @ip_address.handcart.to_s, MangoHandcart.handcart_class.handcart_show_path(@ip_address.handcart)
            - else
              None
        %tr
          %th= MangoHandcart::IpAddress.human_attribute_name(:blacklisted)
          %td= @ip_address.blacklisted? ? "Yes" : "No"
        %tr
          %th Created At
          %td= l(@ip_address.created_at, format: :short)
        %tr
          %th Updated At
          %td= l(@ip_address.updated_at, format: :short)

  .col-lg-9
    Other stuff here